build_targets:
- commands:
  - ./scripts/circle-ci/download-moreutils.sh
  - ./scripts/time-cmd.sh ./gradlew --profile --parallel --stacktrace classes testClasses
  container:
    image: yourbase/yb_ubuntu:18.04
  name: default
  environment:
      - GRADLE_OPTS="-Dorg.gradle.console=plain -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
      - _JAVA_OPTIONS="-XX:ActiveProcessorCount=8 -Xmx8g -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:-TraceClassUnloading -Xloggc:build-%t-%p.gc.log"
      - CIRCLE_TEST_REPORTS=/home/circleci/junit
      - CIRCLE_ARTIFACTS=/home/circleci/artifacts
ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:11.0.6
  - gradle:6.5.1
